// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Context
{
    public partial class Employee
    {
        public Employee()
        {
            User = new HashSet<User>();
        }

        [Key]
        public int EmployeeId { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string MiddleName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateofBirth { get; set; }
        public int? DesignationId { get; set; }
        public bool? IsActive { get; set; }
        public int? EntryBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EntryDate { get; set; }
        public int? UpdateBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }

        [InverseProperty("Employee")]
        public virtual ICollection<User> User { get; set; }
    }
}