// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Context
{
    public partial class User
    {
        public User()
        {
            UserRole = new HashSet<UserRole>();
        }

        [Key]
        public int UserId { get; set; }
        public int? EmployeeId { get; set; }
        [StringLength(50)]
        public string UserName { get; set; }
        [StringLength(50)]
        public string Password { get; set; }
        public bool? IsActive { get; set; }
        public int? EntryBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EntryDate { get; set; }

        [ForeignKey("EmployeeId")]
        [InverseProperty("User")]
        public virtual Employee Employee { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<UserRole> UserRole { get; set; }
    }
}